# Generated by Django 5.1.6 on 2025-02-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarizationhistory',
            old_name='output_text',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='summarizationhistory',
            name='request_type',
        ),
        migrations.AlterField(
            model_name='summarizationhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
