# Generated by Django 4.1.13 on 2025-03-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0003_chathistory_delete_summarizationhistory'),
    ]

    operations = [
    ]
